{
  name: 'Conventional Commit PR Validator',
  description: 'Ensures that either all commit messages or the PR title follow the Conventional Commits standard, labels the PR accordingly.',
  inputs: {
    GITHUB_TOKEN: {
      description: 'GitHub token to access API',
      required: true
    },
    task_types: {
      description: 'Comma-separated list of allowed commit types',
      required: false,
      default: 'feat,fix,docs,test,ci,refactor,perf,chore,build,style,ops'
    },
    add_label: {
      description: 'Whether to add commit type labels to the PR',
      required: false,
      default: 'true'
    },
    add_scope_label: {
      description: 'Whether to add scope-based labels',
      required: false,
      default: 'true'
    },
    custom_labels: {
      description: 'Replaces the short hand types with long names for labels',
      required: false,
      default: '{"feat":"feature","docs":"documentation","ci":"CI/CD","perf":"performance"}'
    },
    link_on_failure: {
      description: 'Adds a link to the error message with a note saying "Read more here: <link>"',
      required: false,
      default: undefined
    }
  },
  runs: {
    using: 'node20',
    main: 'dist/index.js'
  },
  branding: {
    icon: "git-commit",
    color: "blue"
  },
  author: "Fritjof Höst"
}